//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FixedDepositAccount
    {
        public int AccountId { get; set; }
        public int CustomerId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal FD_ROI { get; set; }
        public decimal PrincipalAmount { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
